export default [
  { value: 'English', code: 'en-US' },
  { value: 'Afrikaans', code: 'af' },
  { value: 'Basque', code: 'eu' },
  { value: 'Bulgarian', code: 'bg' },
  { value: 'Catalan', code: 'ca' },
  { value: 'Arabic (Egypt)', code: 'ar-EG' },
  { value: 'Arabic (Jordan) ', code: 'ar-JO' },
  { value: 'Arabic (Kuwait) ', code: 'ar-KW' },
  { value: 'Arabic (Lebanon)', code: 'ar-LB' },
  { value: 'Arabic (Qatar)', code: 'ar-QA' },
  { value: 'Arabic (UAE)', code: 'ar-AE' },
  { value: 'Arabic (Morocco)', code: 'ar-MA' },
  { value: 'Arabic (Iraq)', code: 'ar-IQ' },
  { value: 'Arabic (Algeria)', code: 'ar-DZ' },
  { value: 'Arabic (Bahrain)', code: 'ar-BH' },
  { value: 'Arabic (Lybia)', code: 'ar-LY' },
  { value: 'Arabic (Oman)', code: 'ar-OM' },
  { value: 'Arabic (Saudi Arabia)', code: 'ar-SA' },
  { value: 'Arabic (Tunisia)', code: 'ar-TN' },
  { value: 'Czech', code: 'cs' },
  { value: 'Dutch', code: 'nl-NL' },
  { value: 'Finnish', code: 'fi' },
  { value: 'French', code: 'fr-FR' },
  { value: 'Galician', code: 'gl' },
  { value: 'German', code: 'de-DE' },
  { value: 'Greek', code: 'el-GR' },
  { value: 'Hebrew', code: 'he' },
  { value: 'Hungarian', code: 'hu' },
  { value: 'Icelandic', code: 'is' },
  { value: 'Italian', code: 'it-IT' },
  { value: 'Indonesian', code: 'id' },
  { value: 'Japanese', code: 'ja' },
  { value: 'Korean', code: 'ko' },
  { value: 'Latin', code: 'la' },
  { value: 'Mandarin Chinese', code: 'zh-CN' },
  { value: 'Traditional Taiwan', code: 'zh-TW' },
  { value: 'Simplified Chin', code: 'zh-CN' },
  { value: 'Simplified Hong Kong', code: 'zh-HK' },
  { value: 'Yue Chinese (Traditional Hong Kong)', code: 'zh-yue' },
  { value: 'Malaysian', code: 'ms-MY' },
  { value: 'Norwegian', code: 'no-NO' },
  { value: 'Polish', code: 'pl' },
  { value: 'Portuguese', code: 'pt-PT' },
  { value: 'Portuguese (Brasil)', code: 'pt-BR' },
  { value: 'Romanian', code: 'ro-RO' },
  { value: 'Russian', code: 'ru' },
  { value: 'Serbian', code: 'sr-SP' },
  { value: 'Slovak', code: 'sk' },
  { value: 'Spanish (Argentina)', code: 'es-AR' },
  { value: 'Spanish (Bolivia)', code: 'es-BO' },
  { value: 'Spanish (Chile)', code: 'es-CL' },
  { value: 'Spanish (Colombia)', code: 'es-CO' },
  { value: 'Spanish (Costa Rica)', code: 'es-CR' },
  { value: 'Spanish (Dominican Republic)', code: 'es-DO' },
  { value: 'Spanish (Ecuador)', code: 'es-EC' },
  { value: 'Spanish (El Salvador)', code: 'es-SV' },
  { value: 'Spanish (Guatemala)', code: 'es-GT' },
  { value: 'Spanish (Honduras)', code: 'es-HN' },
  { value: 'Spanish (Mexico)', code: 'es-MX' },
  { value: 'Spanish (Nicaragua)', code: 'es-NI' },
  { value: 'Spanish (Panama)', code: 'es-PA' },
  { value: 'Spanish (Paraguay)', code: 'es-PY' },
  { value: 'Spanish (Peru)', code: 'es-PE' },
  { value: 'Spanish (Puerto Rico)', code: 'es-PR' },
  { value: 'Spanish (Spain)', code: 'es-ES' },
  { value: 'Spanish (US)', code: 'es-US' },
  { value: 'Spanish (Uruguay)', code: 'es-UY' },
  { value: 'Spanish (Venezuela)', code: 'es-VE' },
  { value: 'Swedish', code: 'sv-SE' },
  { value: 'Turkish', code: 'tr' },
  { value: 'Zulu', code: 'zu' },
];

// export default [
//   { 'value': 'English', 'code': 'EN' },
//   { 'value': 'Japanese', 'code': 'JA' },
//   { 'value': 'Afrikaans', 'code': 'AF' },
//   { 'value': 'Albanian', 'code': 'SQ' },
//   { 'value': 'Arabic', 'code': 'AR' },
//   { 'value': 'Armenian', 'code': 'HY' },
//   { 'value': 'Basque', 'code': 'EU' },
//   { 'value': 'Bengali', 'code': 'BN' },
//   { 'value': 'Bulgarian', 'code': 'BG' },
//   { 'value': 'Catalan', 'code': 'CA' },
//   { 'value': 'Cambodian', 'code': 'KM' },
//   { 'value': 'Chinese (Mandarin)', 'code': 'zh-CN' },
//   { 'value': 'Croatian', 'code': 'HR' },
//   { 'value': 'Czech', 'code': 'CS' },
//   { 'value': 'Danish', 'code': 'DA' },
//   { 'value': 'Dutch', 'code': 'NL' },
//   { 'value': 'Estonian', 'code': 'ET' },
//   { 'value': 'Fiji', 'code': 'FJ' },
//   { 'value': 'Finnish', 'code': 'FI' },
//   { 'value': 'French', 'code': 'FR' },
//   { 'value': 'Georgian', 'code': 'KA' },
//   { 'value': 'German', 'code': 'DE' },
//   { 'value': 'Greek', 'code': 'EL' },
//   { 'value': 'Gujarati', 'code': 'GU' },
//   { 'value': 'Hebrew', 'code': 'HE' },
//   { 'value': 'Hindi', 'code': 'HI' },
//   { 'value': 'Hungarian', 'code': 'HU' },
//   { 'value': 'Icelandic', 'code': 'IS' },
//   { 'value': 'Indonesian', 'code': 'ID' },
//   { 'value': 'Irish', 'code': 'GA' },
//   { 'value': 'Italian', 'code': 'IT' },
//   { 'value': 'Javanese', 'code': 'JW' },
//   { 'value': 'Korean', 'code': 'KO' },
//   { 'value': 'Latin', 'code': 'LA' },
//   { 'value': 'Latvian', 'code': 'LV' },
//   { 'value': 'Lithuanian', 'code': 'LT' },
//   { 'value': 'Macedonian', 'code': 'MK' },
//   { 'value': 'Malay', 'code': 'MS' },
//   { 'value': 'Malayalam', 'code': 'ML' },
//   { 'value': 'Maltese', 'code': 'MT' },
//   { 'value': 'Maori', 'code': 'MI' },
//   { 'value': 'Marathi', 'code': 'MR' },
//   { 'value': 'Mongolian', 'code': 'MN' },
//   { 'value': 'Nepali', 'code': 'NE' },
//   { 'value': 'Norwegian', 'code': 'NO' },
//   { 'value': 'Persian', 'code': 'FA' },
//   { 'value': 'Polish', 'code': 'PL' },
//   { 'value': 'Portuguese', 'code': 'PT' },
//   { 'value': 'Punjabi', 'code': 'PA' },
//   { 'value': 'Quechua', 'code': 'QU' },
//   { 'value': 'Romanian', 'code': 'RO' },
//   { 'value': 'Russian', 'code': 'RU' },
//   { 'value': 'Samoan', 'code': 'SM' },
//   { 'value': 'Serbian', 'code': 'SR' },
//   { 'value': 'Slovak', 'code': 'SK' },
//   { 'value': 'Slovenian', 'code': 'SL' },
//   { 'value': 'Spanish', 'code': 'ES' },
//   { 'value': 'Swahili', 'code': 'SW' },
//   { 'value': 'Swedish', 'code': 'SV' },
//   { 'value': 'Tamil', 'code': 'TA' },
//   { 'value': 'Tatar', 'code': 'TT' },
//   { 'value': 'Telugu', 'code': 'TE' },
//   { 'value': 'Thai', 'code': 'TH' },
//   { 'value': 'Tibetan', 'code': 'BO' },
//   { 'value': 'Tonga', 'code': 'TO' },
//   { 'value': 'Turkish', 'code': 'TR' },
//   { 'value': 'Ukrainian', 'code': 'UK' },
//   { 'value': 'Urdu', 'code': 'UR' },
//   { 'value': 'Uzbek', 'code': 'UZ' },
//   { 'value': 'Vietnamese', 'code': 'VI' },
//   { 'value': 'Welsh', 'code': 'CY' },
//   { 'value': 'Xhosa', 'code': 'XH' }
// ];
